#!/usr/bin/env bash
# ============================================================================
# check_flowgap_env.sh — FlowGap Environment Readiness Probe
# ============================================================================
#
# Generated by: docs/prompts/02_codex_environment_probe_plan.md
# Target:       Ascend 910A aarch64 EulerOS / openEuler
#
# READ-ONLY: This script does NOT modify system state.
#            No packages installed. No uprobes attached. No mounts.
#            No kernel settings changed. No daemons started.
#
# Usage:
#   bash scripts/check_flowgap_env.sh          # user-level checks
#   sudo bash scripts/check_flowgap_env.sh     # full checks (needs root)
#
# Outputs:
#   - console: color-coded PASS/WARN/FAIL
#   - logs/check_flowgap_env_YYYYMMDD_HHMMSS.log: full transcript
# ============================================================================

set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
LOG_DIR="$ROOT_DIR/logs"
mkdir -p "$LOG_DIR"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
LOG_FILE="$LOG_DIR/check_flowgap_env_${TIMESTAMP}.log"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

PASS_COUNT=0
WARN_COUNT=0
FAIL_COUNT=0
TOTAL_COUNT=0

# -------------------------------------------------------------------
# helpers
# -------------------------------------------------------------------
log() {
    echo -e "$*" | tee -a "$LOG_FILE"
}

check_pass() {
    local label="$1"
    local detail="${2:-}"
    PASS_COUNT=$((PASS_COUNT + 1))
    TOTAL_COUNT=$((TOTAL_COUNT + 1))
    log "  ${GREEN}[PASS]${NC} $label ${CYAN}$detail${NC}"
}

check_warn() {
    local label="$1"
    local detail="${2:-}"
    WARN_COUNT=$((WARN_COUNT + 1))
    TOTAL_COUNT=$((TOTAL_COUNT + 1))
    log "  ${YELLOW}[WARN]${NC} $label ${CYAN}$detail${NC}"
}

check_fail() {
    local label="$1"
    local detail="${2:-}"
    FAIL_COUNT=$((FAIL_COUNT + 1))
    TOTAL_COUNT=$((TOTAL_COUNT + 1))
    log "  ${RED}[FAIL]${NC} $label ${CYAN}$detail${NC}"
}

# -------------------------------------------------------------------
# header
# -------------------------------------------------------------------
log "======================================================================="
log " FlowGap Environment Probe — $(date)"
log " Log: $LOG_FILE"
log "======================================================================="
log ""

# -------------------------------------------------------------------
# 1. OS and Kernel
# -------------------------------------------------------------------
log "━━━ 1. OS and Kernel ━━━"

if [ -f /etc/os-release ]; then
    OS_NAME=$(grep "^ID=" /etc/os-release | cut -d= -f2 | tr -d '"')
    OS_VERSION=$(grep "^VERSION_ID=" /etc/os-release | cut -d= -f2 | tr -d '"')
    check_pass "OS release" "$OS_NAME $OS_VERSION"
else
    check_fail "OS release" "no /etc/os-release"
fi

KERNEL_VER=$(uname -r 2>/dev/null || echo "")
if [ -n "$KERNEL_VER" ]; then
    K_MAJOR=$(echo "$KERNEL_VER" | cut -d. -f1)
    K_MINOR=$(echo "$KERNEL_VER" | cut -d. -f2)
    if [ "$K_MAJOR" -gt 4 ] || { [ "$K_MAJOR" -eq 4 ] && [ "$K_MINOR" -ge 18 ]; }; then
        check_pass "Kernel version" "$KERNEL_VER"
    else
        check_warn "Kernel version" "$KERNEL_VER (>=4.18 recommended)"
    fi
else
    check_fail "Kernel version" "uname failed"
fi

ARCH=$(uname -m 2>/dev/null || echo "")
if [ "$ARCH" = "aarch64" ]; then
    check_pass "Architecture" "$ARCH"
else
    check_fail "Architecture" "$ARCH (need aarch64)"
fi

# kernel config — try multiple locations
KCONFIG=""
for KC in "/boot/config-${KERNEL_VER}" "/proc/config.gz"; do
    if [ -f "$KC" ] || [ -r "$KC" ]; then
        KCONFIG="$KC"
        break
    fi
done

if [ -n "$KCONFIG" ]; then
    check_pass "Kernel config" "$KCONFIG"
    _read_config() {
        if [ "${KCONFIG##*.}" = "gz" ]; then
            zcat "$KCONFIG" 2>/dev/null | grep "$1" || true
        else
            grep "$1" "$KCONFIG" 2>/dev/null || true
        fi
    }

    BTF=$(_read_config "CONFIG_DEBUG_INFO_BTF=y")
    if [ -n "$BTF" ]; then check_pass "  CONFIG_DEBUG_INFO_BTF" "y"; else check_warn "  CONFIG_DEBUG_INFO_BTF" "not set (bpfcc fallback to kallsyms)"; fi

    BPF_ON=$(_read_config "CONFIG_BPF=y")
    BPF_SYS=$(_read_config "CONFIG_BPF_SYSCALL=y")
    if [ -n "$BPF_ON" ] && [ -n "$BPF_SYS" ]; then check_pass "  CONFIG_BPF + BPF_SYSCALL" "y"; else check_fail "  CONFIG_BPF + BPF_SYSCALL" "missing"; fi

    UPROBE=$(_read_config "CONFIG_UPROBES=y")
    if [ -n "$UPROBE" ]; then check_pass "  CONFIG_UPROBES" "y"; else check_fail "  CONFIG_UPROBES" "missing"; fi

    PERF=$(_read_config "CONFIG_PERF_EVENTS=y")
    if [ -n "$PERF" ]; then check_pass "  CONFIG_PERF_EVENTS" "y"; else check_fail "  CONFIG_PERF_EVENTS" "missing"; fi
else
    check_warn "Kernel config" "not found at /boot/config-${KERNEL_VER} or /proc/config.gz"
fi

# kernel headers
if [ -d "/lib/modules/${KERNEL_VER}/build" ]; then
    check_pass "Kernel headers" "/lib/modules/${KERNEL_VER}/build"
elif [ -d "/usr/src/kernels/${KERNEL_VER}" ]; then
    check_pass "Kernel headers" "/usr/src/kernels/${KERNEL_VER}"
elif ls /usr/src/kernels/*/ 1>/dev/null 2>&1; then
    check_warn "Kernel headers" "found in /usr/src/kernels/ but may not match ${KERNEL_VER}"
else
    check_fail "Kernel headers" "not found"
fi

# BTF vmlinux
if [ -f /sys/kernel/btf/vmlinux ]; then
    check_pass "/sys/kernel/btf/vmlinux" "exists"
else
    check_warn "/sys/kernel/btf/vmlinux" "not found (bpfcc fallback to kallsyms)"
fi

# BPF kernel module
if lsmod 2>/dev/null | grep -q "bpf"; then
    check_pass "BPF kernel module" "loaded"
else
    check_warn "BPF kernel module" "not in lsmod (may still work)"
fi

log ""

# -------------------------------------------------------------------
# 2. eBPF / BCC Toolchain
# -------------------------------------------------------------------
log "━━━ 2. eBPF / BCC Toolchain ━━━"

# Try default python3 first, then system python (/usr/bin/python3) — conda envs may not see yum-installed bpfcc
BPFCC_PY=""
BPFCC_VER="unknown"
if python3 -c "from bpfcc import BPF; print('OK')" 2>/dev/null; then
    BPFCC_PY="python3"
    check_pass "bpfcc Python package" "importable via $(which python3)"
else
    BCC_OK=0
    python3 -c "from bcc import BPF; print('OK')" 2>/dev/null && BCC_OK=1
    if [ "$BCC_OK" -eq 1 ]; then
        BPFCC_PY="python3"
        check_pass "bpfcc Python package" "importable as 'bcc' via $(which python3)"
    elif [ -x /usr/bin/python3 ] && /usr/bin/python3 -c "from bpfcc import BPF; print('OK')" 2>/dev/null; then
        BPFCC_PY="/usr/bin/python3"
        check_warn "bpfcc Python package" "importable via /usr/bin/python3 (NOT via current python3=$(which python3)). Use /usr/bin/python3 or set PYTHONPATH."
    elif /usr/bin/python3 -c "from bcc import BPF; print('OK')" 2>/dev/null; then
        BPFCC_PY="/usr/bin/python3"
        check_warn "bpfcc Python package" "importable as 'bcc' via /usr/bin/python3. Use /usr/bin/python3 or set PYTHONPATH."
    else
        check_fail "bpfcc Python package" "not importable (need python3-bpfcc). Tried: python3=$(which python3), /usr/bin/python3"
    fi
fi

if [ -n "$BPFCC_PY" ]; then
    BPFCC_VER=$($BPFCC_PY -c "import bpfcc; v = getattr(bpfcc, '__version__', None); print(v) if v else print('unknown')" 2>/dev/null || echo "unknown")
fi
check_pass "bpfcc version" "$BPFCC_VER"

if command -v bpftool >/dev/null 2>&1; then
    check_pass "bpftool" "$(bpftool version 2>/dev/null | head -1)"
else
    check_warn "bpftool" "not found"
fi

LIBBPF=$(find /usr -name "libbpf.so*" 2>/dev/null | head -1)
if [ -n "$LIBBPF" ]; then
    check_pass "libbpf.so" "$LIBBPF"
else
    check_warn "libbpf.so" "not found (not required for bpfcc)"
fi

if command -v clang >/dev/null 2>&1; then
    check_pass "clang" "$(clang --version 2>/dev/null | head -1)"
else
    check_fail "clang" "not found (bpfcc needs clang for BPF compilation)"
fi

if command -v llc >/dev/null 2>&1; then
    check_pass "llc" "$(llc --version 2>/dev/null | head -1)"
else
    check_warn "llc" "not found (not strictly required for bpfcc)"
fi

# debugfs tracing
if [ -f /sys/kernel/debug/tracing/uprobe_events ]; then
    check_pass "debugfs tracing" "mounted"
elif [ -d /sys/kernel/debug ]; then
    check_warn "debugfs tracing" "/sys/kernel/debug exists but tracing/ not found"
else
    check_fail "debugfs tracing" "/sys/kernel/debug not accessible"
fi

log ""

# -------------------------------------------------------------------
# 3. CANN / AscendCL SDK
# -------------------------------------------------------------------
log "━━━ 3. CANN / AscendCL SDK ━━━"

ASCEND_HOME="${ASCEND_TOOLKIT_HOME:-}"
if [ -n "$ASCEND_HOME" ]; then
    check_pass "ASCEND_TOOLKIT_HOME" "$ASCEND_HOME"
else
    check_warn "ASCEND_TOOLKIT_HOME" "not set (searching default paths)"
fi

# search paths (matching HostDiagV2's resolve_ascendcl_lib logic)
ASCEND_SEARCH_PATHS=(
    "$ASCEND_HOME/lib64/libascendcl.so"
    "$ASCEND_HOME/aarch64-linux/lib64/libascendcl.so"
    "$ASCEND_HOME/arm64-linux/lib64/libascendcl.so"
    "/usr/local/Ascend/cann-8.5.0/aarch64-linux/lib64/libascendcl.so"
    "/usr/local/Ascend/cann-8.5.0/lib64/libascendcl.so"
    "/usr/local/Ascend/cann-8.5.0/arm64-linux/lib64/libascendcl.so"
    "/usr/local/Ascend/ascend-toolkit/latest/lib64/libascendcl.so"
    "/usr/local/Ascend/ascend-toolkit/latest/aarch64-linux/lib64/libascendcl.so"
    "/usr/local/Ascend/ascend-toolkit/latest/arm64-linux/lib64/libascendcl.so"
    "/usr/local/Ascend/cann/lib64/libascendcl.so"
    "/usr/local/Ascend/cann/aarch64-linux/lib64/libascendcl.so"
    "/usr/local/Ascend/cann/arm64-linux/lib64/libascendcl.so"
)

LIB_ASCENDCL=""
for candidate in "${ASCEND_SEARCH_PATHS[@]}"; do
    if [ -f "$candidate" ]; then
        LIB_ASCENDCL="$candidate"
        break
    fi
done

if [ -z "$LIB_ASCENDCL" ]; then
    # fallback: find
    LIB_ASCENDCL=$(find /usr/local/Ascend -name "libascendcl.so" 2>/dev/null | grep -v devlib | head -1)
fi

if [ -n "$LIB_ASCENDCL" ] && [ -f "$LIB_ASCENDCL" ]; then
    check_pass "libascendcl.so" "$LIB_ASCENDCL"

    FILE_INFO=$(file "$LIB_ASCENDCL" 2>/dev/null)
    log "  file: $FILE_INFO"

    if echo "$FILE_INFO" | grep -q "ELF.*aarch64"; then
        check_pass "  ELF architecture" "aarch64"
    else
        check_fail "  ELF architecture" "not aarch64"
    fi

    if echo "$FILE_INFO" | grep -q "not stripped"; then
        check_pass "  ELF stripped" "not stripped"
    elif echo "$FILE_INFO" | grep -q "stripped"; then
        check_warn "  ELF stripped" "stripped — uprobe may need symbol table; check with nm -D"
    fi

    # resolve CANN version from path
    CANN_DIR=$(dirname "$LIB_ASCENDCL")
    CANN_DIR=$(dirname "$CANN_DIR")
    if [ -f "$CANN_DIR/version.cfg" ]; then
        CANN_VER=$(head -1 "$CANN_DIR/version.cfg" 2>/dev/null)
        check_pass "  CANN version" "$CANN_VER"
    else
        # try one level up
        CANN_PARENT=$(dirname "$CANN_DIR")
        if [ -f "$CANN_PARENT/version.cfg" ]; then
            CANN_VER=$(head -1 "$CANN_PARENT/version.cfg" 2>/dev/null)
            check_pass "  CANN version" "$CANN_VER"
        else
            log "  CANN version: no version.cfg found"
        fi
    fi

    # symbol check — CRITICAL
    log ""
    log "  --- Symbol Checks (nm -D) ---"

    NM_OUT=$(nm -D "$LIB_ASCENDCL" 2>/dev/null)
    if [ -z "$NM_OUT" ]; then
        check_fail "  nm -D" "no output — libascendcl.so may be completely stripped"
    else
        # check each target symbol
        _check_sym() {
            local sym="$1"
            local label="$2"
            local critical="${3:-yes}"
            # Look for exact symbol match as a text symbol (T) or dynamic symbol
            local found
            found=$(echo "$NM_OUT" | grep -E "^[0-9a-f]+ T ${sym}$" | head -1)
            if [ -z "$found" ]; then
                found=$(echo "$NM_OUT" | grep -E " T ${sym}$" | head -1)
            fi
            if [ -z "$found" ]; then
                found=$(echo "$NM_OUT" | grep " ${sym}$" | head -1)
            fi
            if [ -n "$found" ]; then
                local addr=$(echo "$found" | awk '{print $1}')
                local type=$(echo "$found" | awk '{print $2}')
                check_pass "  $label" "addr=$addr type=$type"
            else
                if [ "$critical" = "yes" ]; then
                    check_fail "  $label" "NOT FOUND"
                else
                    check_warn "  $label" "NOT FOUND (optional)"
                fi
            fi
        }

        _check_sym "aclrtMemcpy"          "aclrtMemcpy"            yes
        _check_sym "aclrtSetDevice"        "aclrtSetDevice"         yes
        _check_sym "aclrtMemcpyAsync"      "aclrtMemcpyAsync"       yes
        _check_sym "aclrtSynchronizeStream" "aclrtSynchronizeStream" yes
        _check_sym "aclrtMemcpy2d"         "aclrtMemcpy2d"          no
        _check_sym "aclrtMemcpy2dAsync"    "aclrtMemcpy2dAsync"     no
        _check_sym "aclrtMallocHost"       "aclrtMallocHost"        no
        _check_sym "aclrtMallocDevice"     "aclrtMallocDevice"      no
        _check_sym "aclrtFreeHost"         "aclrtFreeHost"          no
        _check_sym "aclrtFree"             "aclrtFree"              no

        # C++ mangling check
        MANGLED_COUNT=$(echo "$NM_OUT" | grep -c "_Z" 2>/dev/null || echo 0)
        ACL_MANGLED=$(echo "$NM_OUT" | grep "aclrt" | grep -c "_Z" 2>/dev/null || echo 0)
        if [ "$ACL_MANGLED" -eq 0 ]; then
            check_pass "  C ABI (no C++ mangling on aclrt*)" "clean"
        else
            check_warn "  C ABI" "$ACL_MANGLED aclrt* symbols appear mangled"
        fi
    fi
else
    check_fail "libascendcl.so" "NOT FOUND in any search path"
    log "  Searched:"
    for candidate in "${ASCEND_SEARCH_PATHS[@]}"; do
        log "    $candidate"
    done
    log "  Also ran: find /usr/local/Ascend -name libascendcl.so"
fi

# /dev/davinci
DAVINCI_COUNT=$(ls /dev/davinci* 2>/dev/null | wc -l)
if [ "$DAVINCI_COUNT" -gt 0 ]; then
    check_pass "/dev/davinci*" "$DAVINCI_COUNT devices"
else
    check_warn "/dev/davinci*" "no devices (driver not loaded or not Ascend machine)"
fi

# npu-smi
if command -v npu-smi >/dev/null 2>&1; then
    NPU_TOPO=$(npu-smi info -t topo 2>/dev/null | head -20)
    if [ -n "$NPU_TOPO" ]; then
        check_pass "npu-smi" "works"
        log "  --- npu-smi topo snippet ---"
        echo "$NPU_TOPO" | while IFS= read -r l; do log "  $l"; done
        # count HCCS links
        HCCS_COUNT=$(echo "$NPU_TOPO" | grep -o "HCCS" | wc -l)
        log "  HCCS links detected: $HCCS_COUNT"
    else
        check_warn "npu-smi" "found but topology query failed"
    fi
else
    check_warn "npu-smi" "not found"
fi

# Ascend headers
ASCEND_INCLUDES=(
    "$ASCEND_HOME/include/acl/acl.h"
    "$ASCEND_HOME/aarch64-linux/include/acl/acl.h"
    "/usr/local/Ascend/ascend-toolkit/latest/include/acl/acl.h"
    "/usr/local/Ascend/cann-8.5.0/include/acl/acl.h"
    "/usr/local/Ascend/cann-8.5.0/aarch64-linux/include/acl/acl.h"
)
ACL_HEADER=""
for h in "${ASCEND_INCLUDES[@]}"; do
    if [ -f "$h" ]; then ACL_HEADER="$h"; break; fi
done
if [ -z "$ACL_HEADER" ]; then
    ACL_HEADER=$(find /usr/local/Ascend -name "acl.h" -path "*/include/acl/*" 2>/dev/null | head -1)
fi
if [ -n "$ACL_HEADER" ]; then
    check_pass "Ascend headers" "$ACL_HEADER"
else
    check_warn "Ascend headers" "not found in standard paths (needed for probe build)"
fi

log ""

# -------------------------------------------------------------------
# 4. Python Environment
# -------------------------------------------------------------------
log "━━━ 4. Python Environment ━━━"

PYTHON_VER=$(python3 --version 2>/dev/null || echo "")
if [ -n "$PYTHON_VER" ]; then
    PY_MAJOR=$(echo "$PYTHON_VER" | cut -d. -f2)
    if [ "$PY_MAJOR" -ge 8 ]; then
        check_pass "Python" "$PYTHON_VER"
    else
        check_warn "Python" "$PYTHON_VER (>=3.8 recommended)"
    fi
else
    check_fail "Python" "python3 not found"
fi

_check_py_pkg() {
    local mod="$1"
    local label="$2"
    local critical="${3:-no}"
    if python3 -c "import $mod" 2>/dev/null; then
        local ver=$(python3 -c "print(getattr($mod, '__version__', ''))" 2>/dev/null)
        check_pass "$label" "ver=$ver"
    else
        if [ "$critical" = "yes" ]; then
            check_fail "$label" "not importable"
        else
            check_warn "$label" "not importable"
        fi
    fi
}

_check_py_pkg "numpy"       "numpy"       no
_check_py_pkg "sklearn"     "scikit-learn" no
_check_py_pkg "statsmodels" "statsmodels"  no
_check_py_pkg "pandas"      "pandas"       no
_check_py_pkg "matplotlib"  "matplotlib"   no
_check_py_pkg "scipy"       "scipy"        no
_check_py_pkg "aeon"        "aeon"         no

if command -v pip3 >/dev/null 2>&1; then
    check_pass "pip" "$(pip3 --version 2>/dev/null | head -1)"
elif python3 -m pip --version >/dev/null 2>&1; then
    check_pass "pip (python3 -m pip)" "works"
else
    check_warn "pip" "not found"
fi

log ""

# -------------------------------------------------------------------
# 5. Build Tools
# -------------------------------------------------------------------
log "━━━ 5. Build Tools ━━━"

if command -v g++ >/dev/null 2>&1; then
    GXX_VER=$(g++ --version 2>/dev/null | head -1)
    GXX_MAJOR=$(g++ -dumpversion 2>/dev/null | cut -d. -f1)
    if [ "$GXX_MAJOR" -ge 8 ]; then
        check_pass "g++" "$GXX_VER"
    else
        check_warn "g++" "$GXX_VER (>=8 recommended for C++11)"
    fi
else
    check_fail "g++" "not found"
fi

if command -v cmake >/dev/null 2>&1; then
    check_pass "cmake" "$(cmake --version 2>/dev/null | head -1)"
else
    check_warn "cmake" "not found (build.sh fallback works without cmake)"
fi

if command -v make >/dev/null 2>&1; then
    check_pass "make" "$(make --version 2>/dev/null | head -1)"
else
    check_warn "make" "not found"
fi

# libnuma
NUMA_H=""
for nh in "/usr/include/numa.h" "/usr/local/include/numa.h"; do
    [ -f "$nh" ] && { NUMA_H="$nh"; break; }
done
[ -z "$NUMA_H" ] && NUMA_H=$(find /usr -name "numa.h" 2>/dev/null | head -1)
if [ -n "$NUMA_H" ]; then
    check_pass "libnuma headers" "$NUMA_H"
else
    check_warn "libnuma headers" "not found (needed for probe executor)"
fi

NUMA_SO=$(find /usr -name "libnuma.so*" 2>/dev/null | head -1)
if [ -n "$NUMA_SO" ]; then
    check_pass "libnuma library" "$NUMA_SO"
else
    check_warn "libnuma library" "not found"
fi

PTHREAD_SO=$(find /usr -name "libpthread*" 2>/dev/null | head -1)
if [ -n "$PTHREAD_SO" ]; then
    check_pass "libpthread" "$PTHREAD_SO"
else
    check_warn "libpthread" "not found"
fi

log ""

# -------------------------------------------------------------------
# 6. Topology and Hardware
# -------------------------------------------------------------------
log "━━━ 6. Topology and Hardware ━━━"

if command -v lscpu >/dev/null 2>&1; then
    CPU_MODEL=$(lscpu 2>/dev/null | grep "Model name" | cut -d: -f2 | xargs)
    CPU_COUNT=$(lscpu 2>/dev/null | grep "^CPU(s):" | awk '{print $2}')
    check_pass "CPU" "$CPU_COUNT cores $CPU_MODEL"
else
    CPU_COUNT=$(grep -c "^processor" /proc/cpuinfo 2>/dev/null || echo "?")
    check_pass "CPU" "$CPU_COUNT cores"
fi

if command -v numactl >/dev/null 2>&1; then
    NUMA_NODES=$(numactl --hardware 2>/dev/null | grep "available" | awk '{print $2}')
    if [ -n "$NUMA_NODES" ]; then
        check_pass "NUMA topology" "$NUMA_NODES nodes"
    else
        check_warn "NUMA topology" "numactl failed"
    fi
else
    NUMA_SYSFS=$(ls -d /sys/devices/system/node/node[0-9]* 2>/dev/null | wc -l)
    if [ "$NUMA_SYSFS" -gt 0 ]; then
        check_pass "NUMA topology" "$NUMA_SYSFS nodes (from sysfs)"
    else
        check_warn "NUMA topology" "could not determine"
    fi
fi

MEM_TOTAL=$(grep MemTotal /proc/meminfo 2>/dev/null | awk '{printf "%.0f", $2/1024/1024}')
if [ -n "$MEM_TOTAL" ]; then
    if [ "${MEM_TOTAL%.*}" -ge 32 ]; then
        check_pass "Memory" "${MEM_TOTAL} GB"
    else
        check_warn "Memory" "${MEM_TOTAL} GB (<32 GB may be tight)"
    fi
else
    check_warn "Memory" "could not parse /proc/meminfo"
fi

if [ "$DAVINCI_COUNT" -gt 0 ]; then
    if [ "$DAVINCI_COUNT" -ge 4 ]; then
        check_pass "NPU count" "$DAVINCI_COUNT"
    else
        check_warn "NPU count" "$DAVINCI_COUNT (<4)"
    fi
else
    check_warn "NPU count" "could not determine"
fi

# PCIe Ascend devices
if command -v lspci >/dev/null 2>&1; then
    PCI_ASCEND=$(lspci 2>/dev/null | grep -i -E "ascend|npu|coherent|da vinci" | wc -l)
    if [ "$PCI_ASCEND" -gt 0 ]; then
        check_pass "PCIe Ascend devices" "$PCI_ASCEND"
    else
        log "  lspci did not list Ascend devices (not unusual for ARM)"
    fi
fi

log ""

# -------------------------------------------------------------------
# 7. Permissions
# -------------------------------------------------------------------
log "━━━ 7. Permissions ━━━"

CURRENT_USER=$(whoami 2>/dev/null || echo "unknown")
if [ "$CURRENT_USER" = "root" ]; then
    check_pass "User" "root"
else
    check_warn "User" "$CURRENT_USER (root or CAP_BPF needed for eBPF)"
fi

# kernel.unprivileged_bpf_disabled
BPF_DISABLED=$(sysctl -n kernel.unprivileged_bpf_disabled 2>/dev/null || echo "unknown")
if [ "$BPF_DISABLED" = "0" ]; then
    check_pass "kernel.unprivileged_bpf_disabled" "0"
elif [ "$BPF_DISABLED" = "unknown" ]; then
    check_warn "kernel.unprivileged_bpf_disabled" "could not read"
else
    check_warn "kernel.unprivileged_bpf_disabled" "$BPF_DISABLED (1 = unpriv disabled, root still works)"
fi

# debugfs
if [ -d /sys/kernel/debug ]; then
    if ls /sys/kernel/debug/tracing/events/ 1>/dev/null 2>&1; then
        check_pass "/sys/kernel/debug" "accessible"
    else
        check_warn "/sys/kernel/debug" "directory exists but tracing/events not readable"
    fi
else
    check_warn "/sys/kernel/debug" "not mounted"
fi

# perf_event_paranoid
PERF_PARANOID=$(cat /proc/sys/kernel/perf_event_paranoid 2>/dev/null || echo "unknown")
if [ "$PERF_PARANOID" = "unknown" ]; then
    check_warn "perf_event_paranoid" "could not read"
elif [ "$PERF_PARANOID" -le 2 ]; then
    check_pass "perf_event_paranoid" "$PERF_PARANOID (<=2 OK)"
else
    check_fail "perf_event_paranoid" "$PERF_PARANOID (>2 blocks BPF perf output)"
fi

# kptr_restrict
KPTR=$(cat /proc/sys/kernel/kptr_restrict 2>/dev/null || echo "unknown")
if [ "$KPTR" = "unknown" ]; then
    check_warn "kptr_restrict" "could not read"
elif [ "$KPTR" -le 1 ]; then
    check_pass "kptr_restrict" "$KPTR (<=1 OK)"
else
    check_warn "kptr_restrict" "$KPTR (=2 hides kernel pointers)"
fi

# ulimit
ULIMIT_L=$(ulimit -l 2>/dev/null || echo "unknown")
if [ "$ULIMIT_L" = "unlimited" ]; then
    check_pass "ulimit -l" "unlimited"
elif [ "$ULIMIT_L" = "unknown" ]; then
    check_warn "ulimit -l" "could not determine"
else
    check_warn "ulimit -l" "$ULIMIT_L (unlimited preferred for BPF maps)"
fi

log ""

# -------------------------------------------------------------------
# 8. Process Environment
# -------------------------------------------------------------------
log "━━━ 8. Process Environment ━━━"

ASCEND_PROCS=$(ps aux 2>/dev/null | grep -E "acl|ascend|npu" | grep -v grep | grep -v check_flowgap | wc -l)
if [ "$ASCEND_PROCS" -gt 0 ]; then
    check_pass "AscendCL processes" "$ASCEND_PROCS running"
    log "  --- sample ---"
    ps aux 2>/dev/null | grep -E "acl|ascend|npu" | grep -v grep | grep -v check_flowgap | head -5 | while IFS= read -r l; do log "  $l"; done
else
    log "  No AscendCL-related processes running (expected on dev machine)"
fi

LD_PATH="${LD_LIBRARY_PATH:-}"
if [ -n "$LD_PATH" ]; then
    if echo "$LD_PATH" | grep -q "Ascend" 2>/dev/null; then
        check_pass "LD_LIBRARY_PATH" "includes Ascend path"
    else
        check_warn "LD_LIBRARY_PATH" "does not include Ascend path"
    fi
else
    check_warn "LD_LIBRARY_PATH" "not set"
fi

if [ -w /tmp ]; then
    check_pass "/tmp" "writable"
else
    check_warn "/tmp" "not writable"
fi

log ""

# -------------------------------------------------------------------
# Summary
# -------------------------------------------------------------------
log "======================================================================="
log " SUMMARY"
log "======================================================================="
log "  PASS: $PASS_COUNT"
log "  WARN: $WARN_COUNT"
log "  FAIL: $FAIL_COUNT"
log "  TOTAL: $TOTAL_COUNT"
log "  Log:  $LOG_FILE"
log "======================================================================="

if [ "$FAIL_COUNT" -eq 0 ]; then
    log ""
    log "${GREEN}Environment looks good! No blockers found.${NC}"
    log "You can proceed with Patch 1 (eBPF hooks) and Patch 2 (probe executor)."
    if [ "$WARN_COUNT" -gt 0 ]; then
        log "Review $WARN_COUNT warnings above for optional improvements."
    fi
elif [ "$FAIL_COUNT" -le 3 ]; then
    log ""
    log "${YELLOW}Partial readiness — $FAIL_COUNT blockers found.${NC}"
    log "Review FAIL items above and resolve before proceeding."
else
    log ""
    log "${RED}$FAIL_COUNT blockers found — environment is not ready for FlowGap development.${NC}"
    log "Resolve all FAIL items before proceeding."
fi

exit $FAIL_COUNT
